apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  namespace: trino
data:
  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=hadoop
    iceberg.catalog.warehouse=s3a://warehouse/
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.region=us-east-1
