apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-connect
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-connect
  template:
    metadata:
      labels:
        app: iceberg-connect
    spec:
      containers:
      - name: connect
        image: docker.io/h4rkon/iceberg-connect:latest
        ports:
          - containerPort: 8083
        env:
          - name: BOOTSTRAP_SERVERS
            value: "redpanda.kafka.svc.cluster.local:9092"
          - name: GROUP_ID
            value: "iceberg-connect"
          - name: AWS_ACCESS_KEY_ID
            value: "minioadmin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minioadmin"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_EC2_METADATA_DISABLED
            value: "true"
          - name: HADOOP_CONF_DIR
            value: "/etc/hadoop"
          - name: KAFKA_OPTS
            value: "-Dfs.s3a.endpoint=http://minio.minio.svc.cluster.local:9000 -Dfs.s3a.connection.ssl.enabled=false -Dfs.s3a.path.style.access=true -Dfs.s3a.access.key=minioadmin -Dfs.s3a.secret.key=minioadmin -Dfs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider -Dfs.s3a.endpoint.region=us-east-1 -Dfs.s3a.region=us-east-1"
          - name: CONFIG_STORAGE_TOPIC
            value: "iceberg-connect-configs"
          - name: OFFSET_STORAGE_TOPIC
            value: "iceberg-connect-offsets"
          - name: STATUS_STORAGE_TOPIC
            value: "iceberg-connect-status"
          - name: CONFIG_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: OFFSET_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: STATUS_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: VALUE_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: KEY_CONVERTER_SCHEMAS_ENABLE
            value: "false"
          - name: VALUE_CONVERTER_SCHEMAS_ENABLE
            value: "false"
          - name: REST_ADVERTISED_HOST_NAME
            value: "iceberg-connect"
          - name: REST_PORT
            value: "8083"
          - name: LOG_LEVEL
            value: "INFO"
        volumeMounts:
          - name: hadoop-config
            mountPath: /etc/hadoop
            readOnly: true
      volumes:
        - name: hadoop-config
          configMap:
            name: iceberg-connect-hadoop-config
